### PR TITLE
For PyPI, add the supported versions of Python

### PR DESCRIPTION
**Pull request by cclauss**
Are these the right versions?

### CODE REVIEW

**Comment by cclauss** [comment]
I signed it!

**Comment by vrusinov** [comment]
Sorry, I only saw your pull request now.

I am very sorry but we don't have technical ability to merge pull requests back (see https://github.com/google/python-gflags/blob/master/CONTRIBUTING.md). Can you please describe what are you trying to fix and I'll try to address in in next release?

**Comment by cclauss** [comment]
The problem that I am trying to fix is that python-gflags is currently on the [Python 3 Wall of Shame](https://python3wos.appspot.com/).  As one of the top 200 modules downloaded from PyPI, python-gflags is highly visible.  python-gflags is on python3wos because I believe that its PyPI record does not properly declare its Python 3 compatibility.  If python-gflags is not compatible with Python 3 then it should be in red but if it does indeed support Python 3, the it should be in green.

**Comment by vrusinov** [comment]
Gotcha. I'll run a few tests with python3 and update setup accordingly.

**Comment by nickjacobson** [comment]
The changes in https://github.com/google/python-gflags/pull/22 could make the library Python 3 compatible.

**Comment by vrusinov** [comment]
Status update: I've declared python-gflags python2 only.
While I can make it "work" in python3 I would not be comfortable declaring it is supported. There are few fundamental changes needs to be done, specifically in bytes vs unicode/str area.

Since we don't have ability to accept pull requests to this project, I'm going to close this one and continue working on proper python3 support.

**Comment by Kurt-von-Laven** [comment]
Thank you for investigating Python 3 support, @vrusinov. Would it be possible to get a rough ETA? Is [Ubuntu's version of gflags that supports Python 3](http://packages.ubuntu.com/xenial/python3-gflags) already on your radar?

**Comment by vrusinov** [comment]
For anyone may see this pull request: I think Gregory summarized situation quite accurately in issue #20.

**Pull request closed without merging**
